mysql:
  dns: root:1234567890@tcp(127.0.0.1:3306)/wa_chat?charset=utf8mb4&parseTime=True&loc=Local
redis:
  addr: "127.0.0.1:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConn: 30
port:
  server: ":8082"
  udp: 3001